### PR TITLE
Feature to select specific country, city, state

### PR DESCRIPTION
**Pull request by BilelJegham**
Hello,
I made a feature to select only specific country, city, state. 

# Add:
## SearchBar on HomePage
image
## Custom geojson
I had feature to make custom map with Geojson Polygon
image

image

Example : biggestCitymap.geojson https://gist.github.com/BilelJegham/7f855024440c67d65f24536c9215719e#file-map-geojson
Link :  [GeoJsonEditor](geojson.io)

# Fix: 
1. Fix Montserrat Font

### CODE REVIEW

**Comment by spider-hand** [comment]
Sorry I will not add new features to my repository currently. I want to keep this game as simple as possible.  Fixing bugs is always welcome.

**Comment by BilelJegham** [comment]
Ok it's unfortunate.
I will share my repo to get some feadback

**Comment by spider-hand** [comment]
I will try yours and review when I am free. I have been a bit busy and working on other stuff so might take time.

**Comment by spider-hand** [comment]
Hey I actually tried your version out from your repository and I found out there are a couple of issues.  Here is my feedback.
First, for your version, looks like a lot of layouts are messed up, especially on mobile. 

The button sizes are differenct and it looks weird..


Some extra white spaces on the bottom of the page and exposing environmental variable makes no sense..


The game UI on mobile is not clean in my opinion..


Second, I think your implementation of the custom map is amazing but, according to Nominatim Usage Policy, 

> Unacceptable Use
The following uses are strictly forbidden and will get you banned:
> Auto-complete search This is not yet supported by Nominatim and you must not implement such a service on the client side using the API.

I think your implementaiton violates this part.  You have to get rid of the search suggestion functionality.
Also, in my opinion, asking users to edit GeoJSON file is not good in terms of UX and UI because most users are supposed to have no idea what GeoJSON file is.

Hope my feedback is helpful.

**Comment by BilelJegham** [comment]
Thanks for your feedback, I took the time to fix on the master branch. (https://geoguess2.netlify.app/)
- Buttons Home responsible **fixed**
- Version **delete**, this was to fix some issue with cache  https://stackoverflow.com/questions/54145735/vue-pwa-not-getting-new-content-after-refresh
- Button "Reset" responsible **fixed** @simonrousseau #6 

For autocomplete, I change API consumed http://photon.komoot.de/.
Used in leaflet autocomplete (https://github.com/komoot/leaflet.photon )

I wish to keep the feature "custom GeoJSON"; because I don't think complicates to use geojson editor like http://geojson.io/. 
I think sharing maps would be great to form and animate the GeoGuess community.

**Pull request closed without merging**
